version: '3'
services:
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - app/node_modules
      - ./client:/app
  nginx:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    links:
      - mongodb
    environment:
      - MONGOURI= mongodb
      - JWT_SECRET
