version: '3.1'
services:
  mongodb:
    container_name: mongo
    image: 'mongo'
    ports:
      - '27017:27017'
  
  client:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
  
  nginx:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    links:
      - mongodb
    environment:
      - NODE_ENV='ci'
      - MONGO_CLIENT= mongodb
      - JWT_SECRET
