apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: worthero-com
spec:
  secretName: worthero-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: worthero.com
  dnsNames:
  - worthero.com
  - www.worthero.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - worthero.com
      - www.worthero.com
