apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchlabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: rahulgupta1199/worthero-server
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: prod
            - name: MONGOHOST
              value: mongodb-cluster-ip-service
            - name: MONGOPORT
              value: '27017'
            - name: MONGODBNAME
              value: worthero
            